### ISSUE TITLE
[1.18.2] AE2 integration, weird CPU Name

### ISSUE THREAD

**Issue by MSandro** [SirEdvin/UnlimitedPeripheralWorks#10]
I've tried to figure out how to set a specific CPU for scheduleCrafting, but was not able to do.
Now I've found the weird name.
![image](https://user-images.githubusercontent.com/10937159/224257167-9d1b5036-a62e-4fe5-a0e5-91c57707fed6.png)
in addition I would like to suggest a craftingOutput Variable for CPUs if it is busy.
I would like to create a crafting request script, and it would be really useful to know if a request for the item is already being processed.

**Comment by MSandro** [comment]
any help?
even if I save the name in a variable, and provide the exact name string to scheduleCrafting, it returns
```
false
nil
```
can anyoine confirm this issue?

**Comment by SirEdvin** [comment]
This seems as a simple issues to fix, I will try to fix this in this week.

**Comment by MSandro** [comment]
thank you very much. Thanks for your good work, I like the mod very much.

**Comment by SirEdvin** [comment]
So ... this will be fixed with next release. You will get proper CPU name and specifing this name as parameter in `scheduleCrafing` also works fine.
Also, there is new method `getAvailableCraftings` will be in place, that allow you to inspect current active craftings in your system.

**Comment by MSandro** [comment]
Great, thank you very much
