### ISSUE TITLE
Suggestion: Modern Industrialization Energy support?

### ISSUE THREAD

**Issue by MSandro** [SirEdvin/UnlimitedPeripheralWorks#12]
it would be great to read energy data from MI Machines.
or maybe the Overclock value as well.

Or maybe adding some general way to read any Block NBT Data.
So we could have a similar output like from the Vanilla Data command `/data get block 2 65 -93`
but this might be a suggestion for the Turtlematic Mod. to have something like turtle.getBlockData()

**Comment by SirEdvin** [comment]
So, this will be done in comming release :) 
Not sure about overclocking, but I will try. 

If you want for something else, please, also let me know, I am not a big expert on fabric mods.

**Comment by SirEdvin** [comment]
Yep, overclocking also in the next patch
