### ISSUE TITLE
[Feature Request] Turtle MultiTool peripheral

### ISSUE THREAD

**Issue by Merith-TK** [SirEdvin/UnlimitedPeripheralWorks#14]
Basically just an peripheral that can hold up to three peripherals (non-stacking),

could hold an modem, pickaxe, and an crafting table, for example, 

peripherals inside an multitool would be accessible by wrapping the multitool and either of these
```lua
local multi = peripheral.find("multitool")

-- This would look for the modem peripheral inside the multitool and return it
local modem = multi.find("modem") 

-- or
local modem = multi.modem
```

**Comment by SirEdvin** [comment]
That would be really cool, but ... I need someone who be able to write curse GUI code :) 

Or at least draw a GUI image for me

**Comment by Merith-TK** [comment]
what kind of GUI are we talking here?

**Comment by SirEdvin** [comment]
As I understand, you what this to work like a bag of peripherals. 
So, some gui to put peripheral items into multitool required. 

Like basically any container GUI, but for 3 or 5 or more elements. 

For some reason, I am catastropically bad at anything that related to any kind of GUI or rendering tricks in code

**Comment by Merith-TK** [comment]
while a "bag of peripherals" would be neat, that would require alteration of the CC mod itself, due to the fact (to my knowledge) 
that peripherals in their current implementation cannot have NBT, so this would be something that would need to be an craftable item, like the paxel mods

shapeless crafting for up to three peripherals 

MultiTool Container
Up to 3x Turtle Peripherals,
(I could probably make a tool to run to automatically generate these within the mod code when provided an table of `modid:item_id`s)

**Comment by SirEdvin** [comment]
Due to https://github.com/cc-tweaked/CC-Tweaked/issues/847 being so blocker for me, I will have bypass logic in place in any case, so this shouldn't be a problem.

For example, if you would take turtle upgrades from this mod and base game, it will just explode all registry related to peripheral logic.

**Comment by SirEdvin** [comment]
Another idea, which I probably will use for peripheral, is consuming peripheral item.

So, first you equip "MultiTool". Then, you "consume" another peripheral item from turtle inventory and it automatically appear as peripheral inside turtle. With some limitation, I guess, but it should work just fine. 
Of course, in case of careless unequipment all "consumed" peripherals will be lost, but I guess, we can go with this.

**Comment by SirEdvin** [comment]
So ... this feature was implemented as part of UPW. [Peripheralium hub](https://docs.siredvin.site/UnlimitedPeripheralWorks/peripherals/peripheralium_hub/) that works with turtles as well as pocket computers can fix this gap. 
Unfortunatly, not with tools for now, and probably will not.

**Comment by Merith-TK** [comment]
Honestly, even without being able to use "tools", this alone will be so much better
