### ISSUE TITLE
More precise create storages integration for 1.18/1.19

### ISSUE THREAD

**Issue by SirEdvin** [SirEdvin/UnlimitedPeripheralWorks#16]
So, following up this [issue](https://github.com/SirEdvin/Peripheralium/issues/6), it would be nice to create better Create integration for storages. 

It would be also nice to get more familiar with create codebase, so why not.

**Comment by SirEdvin** [comment]
So .... is it done.

@WillowMist, please, take a test for new 0.2.7 version.

**Comment by WillowMist** [comment]
Looks great.  I did notice that a single itemvault block appears to have a size of 20.  Is that correct?

**Comment by SirEdvin** [comment]
Seems correct according to create [default configuration](https://github.com/Fabricators-of-Create/Create/blob/mc1.18/fabric/dev/src/main/java/com/simibubi/create/infrastructure/config/CLogistics.java#L12).
