### ISSUE TITLE
[feature] AE2 Peripheral Support

### ISSUE THREAD

**Issue by Merith-TK** [SirEdvin/UnlimitedPeripheralWorks#2]
Two things!

1) Make computercraft able to use AE2 Fluix Cables as networking cables (one lane per peripheral)

2) Make CC See AE2 P2P connections as peripherals

![image](https://user-images.githubusercontent.com/10422110/177624743-f2e24755-907f-4a8a-b082-94b92f070617.png)
currently this is how one has to setup CC and AE2 networks

AE2 can handle item, power, and etc transportation, it would be amazing if it could handle transportation of CC data as well!

**Comment by SirEdvin** [comment]
I am not sure if this possible, but I will check)

**Comment by Merith-TK** [comment]
Idea for implementation could be an AE2 specific CC Modem (like the ones shown)

**Comment by TheDrawingCoder-Gamer** [comment]
Forge can do this afaik via open peripherals, but there is no equivilant on fabric.

**Comment by TheDrawingCoder-Gamer** [comment]
I'm not necessarily a fan of kotlin, so I'll write my own mod that works in a lang I prefer.

**Comment by SirEdvin** [comment]
You actually, can write things on java with kotlin repository. It will be a little strange, but defenetly possible

**Comment by SirEdvin** [comment]
So, sorry, but I decided this to be a little out of scope. 
While idea is defenetly cool, I am not a big fun of implementing it myself.
