### ISSUE TITLE
Reality Forger can only use forgeRealityPieces on anchors outside of radius

### ISSUE THREAD

**Issue by joshmanisdabomb** [SirEdvin/UnlimitedPeripheralWorks#23]
# Intro
Any anchors within the interaction radius of the reality forger cannot be modified with `forgeRealityPieces()`, while anchors outside the interaction radius (which won't be reported by `detectAnchors()`) can be modified by the forger. I expected this to be the other way around.

# Example
![image](https://github.com/SirEdvin/UnlimitedPeripheralWorks/assets/5678121/b8649603-1341-4ba2-a8c4-5c8787cfa0cd)

(There's a second reality forger connected via modem. It's located 40 blocks above the reality anchor, outside the default 24 block limit.)

I would expect the forger directly connected to the computer to be able to modify the anchor below, but this error message is given:

![image](https://github.com/SirEdvin/UnlimitedPeripheralWorks/assets/5678121/3a04208b-a727-46b5-adb3-6ed0d914f22e)

And I would expect the forger connected above to be too far away to modify the anchor, but it works:

![image](https://github.com/SirEdvin/UnlimitedPeripheralWorks/assets/5678121/a94792d7-6d1a-48b9-b7eb-9a28ae2359c6)

(You can see the anchor in the background has changed to cobblestone as well.)

# Conclusion
A quick glance of the code looks like this if statement needs to be inverted:
https://github.com/SirEdvin/UnlimitedPeripheralWorks/blob/8bcce235359c0ace6b83f7285651759910f8b2e1/projects/core/src/main/kotlin/site/siredvin/peripheralworks/computercraft/peripherals/RealityForgerPeripheral.kt#L122C17-L122C30

I didn't see this already in the issues list but apologies if this has already been reported.

I'm using version 1.1.0 on Fabric.

**Comment by SirEdvin** [comment]
I am so sorry about such stupid bugs! 

Thanks for reporting, I am always appreciate anyone who use my mods and have a wish and time to report bugs!

Will fix soon

**Comment by SirEdvin** [comment]
Fixed in 1.1.1
