### ISSUE TITLE
1.19.2 - Incompatable with latest MI release

### ISSUE THREAD

**Issue by TheStaticVoid** [SirEdvin/UnlimitedPeripheralWorks#25]
Modern Industrialization has moved away from using Megane in the latest update, causing the following crash when attempting to place a Computer next to an MI machine:
[crash-2023-08-01_16.55.04-server.txt](https://github.com/SirEdvin/UnlimitedPeripheralWorks/files/12232246/crash-2023-08-01_16.55.04-server.txt)

https://github.com/AztechMC/Modern-Industrialization/pull/516

**Comment by SirEdvin** [comment]
Hello, sorry for report and sorry for long delay. I will try to fix this issue today ...

**Comment by SirEdvin** [comment]
Fixed in 0.2.10, released on curseforge and modrinth.

Thanks for report!
