### ISSUE TITLE
(Fabric) Plethora issue

### ISSUE THREAD

**Issue by awesomebossdj7** [SirEdvin/UnlimitedPeripheralWorks#26]
messing around with this mod and plethora, and noticed that the plethora modules dont work inside of the peripheralium hub because 
"not attached to this computer"

![image](https://github.com/SirEdvin/UnlimitedPeripheralWorks/assets/70352423/403bee3f-15e9-4842-b91e-e4538b4623a5)

**Comment by awesomebossdj7** [comment]
this might be how plethora is programmed, if it is ill report it to them

**Comment by SirEdvin** [comment]
Hey, thanks for report! Unfortunately, I will able to process this only after end of Blanketcon :)

**Comment by SirEdvin** [comment]
So, issue was that I attach actual IComputerAccess instead of wrapped one (because for wired modems you usually need wrap it with extra logic).
This is fixed in 1.4.0 release
