### ISSUE TITLE
Sending data to Integrated Dynamics network broken

### ISSUE THREAD

**Issue by Mareckoo01** [SirEdvin/UnlimitedPeripheralWorks#28]
"Directory inside computer" aspect in Machine Reader is a List type but it outputs NBT.

Using operators on it that expect List as input give error that NBT was given as input.
Using operators on it that expect NBT as input give error that List was given as input.

I'm pretty sure the aspect should be NBT type and not List type.

**Comment by SirEdvin** [comment]
Oh, that is bad. I will take a look, thanks for report

**Comment by SirEdvin** [comment]
Fixed in 1.4.1
