### ISSUE TITLE
[bug] returns wrong error when item_storage is full

### ISSUE THREAD

**Issue by Merith-TK** [SirEdvin/UnlimitedPeripheralWorks#3]
![image](https://user-images.githubusercontent.com/10422110/183150931-387a4f90-ea7e-4bde-a15d-43000fdc1d73.png)

before and after I increased item_storage size

**Comment by SirEdvin** [comment]
I can't reproduce it with described case (works for me and ExtenderDrawer), so I need more detail. Or world copy, if this possible :)

**Comment by Merith-TK** [comment]
Was using Create item Vaults

**Comment by SirEdvin** [comment]
So ... I will close this for now, because I wan't able to reproduce this properly ...

**Comment by Merith-TK** [comment]
IIRC I had two create item vaults
Left was filled to the max
Right wasnt

I tried to `right.PullItem("left")`

if I recall correctly that is

**Comment by SirEdvin** [comment]
I will take a look after porting everything to 1.19.4, I guess :)

**Comment by SirEdvin** [comment]
So, this is happening because now or in older versions create not always correctly processing fabric requests (I suppose).

Due to #16 this issue is not longer relevant, because create integration will be in place
