### ISSUE TITLE
"You are not attached to this computer" with Arcane pedestals

### ISSUE THREAD

**Issue by SirEdvin** [SirEdvin/UnlimitedPeripheralWorks#31]
From this [issue](https://github.com/cc-tweaked/CC-Tweaked/issues/1645)

**Comment by bananasov** [comment]
Also happens on UnlimitedPeripheralWorks v1.4.3 Fabric 1.20.1, [error.txt](https://github.com/SirEdvin/UnlimitedPeripheralWorks/files/14607451/error.txt).

Mod list:
- UnlimitedPeripheral Works v1.4.3
- Ducky Peripherals v1.20.1-1.3.1
- Peripheralium v0.6.15
- [Brewin' And Chewin' [Fabric]](https://www.curseforge.com/minecraft/mc-mods/brewin-and-chewin-fabric)

Trying to use Brewin' and Chewin' kegs with CC and i keep getting the error attached above no matter what.

**Comment by SirEdvin** [comment]
Fixed in 1.4.4 release

**Comment by MrReps** [comment]
Thanks :)
