### ISSUE TITLE
Recent CC:T API change (EncodedReadableHandle -> WriteHandle) causing crashes in IntegratedDynamics compat

### ISSUE THREAD

**Issue by shBLOCK** [SirEdvin/UnlimitedPeripheralWorks#32]
Problem: crash when saving a file in `/integrateddynamics` folder with a machine reader reading that aspect.

Exception:
java.lang.NoClassDefFoundError: dan200/computercraft/core/apis/handles/EncodedReadableHandle
        at site.siredvin.peripheralworks.integrations.integrateddynamics.Integration.collectFileValues(Integration.kt:74)

Cause: [recent API rename](https://github.com/cc-tweaked/CC-Tweaked/commit/0c0556a5bc4066c89aef0db60bdcb05ff093f96d)

**Comment by SirEdvin** [comment]
Thanks for report!

**Comment by SirEdvin** [comment]
So, I would release fix for this issue to the end of the week, but you can take new peripheralium and new UPW from github releases, if you want to test it or use it before official release

**Comment by SirEdvin** [comment]
Fixed in new release
