### ISSUE TITLE
Recipe registry not working properly

### ISSUE THREAD

**Issue by Reubi0910** [SirEdvin/UnlimitedPeripheralWorks#34]
on version 1.4.3 in 1.20.1 with CC:T 1.109.7 on fabric

trying to get all the recipes returns nothing and trying to get the recipes for a single item throws a java error
![image](https://github.com/SirEdvin/UnlimitedPeripheralWorks/assets/67862861/e010934c-1f92-4ac4-bd8a-7ff4bf2f51bf)

**Comment by SirEdvin** [comment]
Thanks for report!

**Comment by SirEdvin** [comment]
Fixed in 1.4.4 release
