### ISSUE TITLE
[Feature request] Allow for getting raw registry ids with Informative registry

### ISSUE THREAD

**Issue by tehgreatdoge** [SirEdvin/UnlimitedPeripheralWorks#36]
This would be useful for projects that need to efficiently store data that is part of a disk persisted registry. (e.g., the block ids in a scan of the world)

**Comment by SirEdvin** [comment]
Hm .. what do you mean with raw registry id?

**Comment by tehgreatdoge** [comment]
as in, the internal int ids that ResourceLocations get mapped to.

**Comment by SirEdvin** [comment]
I am not sure, but internal id probably are not persistant between server restarts, but I will check.

**Comment by tehgreatdoge** [comment]
Both forge and fabric save registries, but it varies between loader as to which registries are. It seems that fabric only persists potion effects, while forge persists all registries by default, with things related to entities (but not entities themselves), rendering, or world generation having it explicitly disabled.

**Comment by SirEdvin** [comment]
Fixed in 1.4.4 release
