### ISSUE TITLE
Can't get items from AE2 ME System

### ISSUE THREAD

**Issue by EugeneLagonski** [SirEdvin/UnlimitedPeripheralWorks#37]
The items function returns an empty table but I have items in the ME system
```lua
me = peripherals.find('ae2:energy_acceptor')
items = me.items()
items
{}
```
It is the first time I have used computer craft. Please let me know if I do something wrong.

Minecraft version: 1.20.1
Modpack: All of Forge 7 2.2.3
AE2 version: 15.2.0
Peripheralium version: 0.6.15
Unlimited Peripheral Works version: 1.4.3

**Comment by SirEdvin** [comment]
So, rather for this is because you using `ae2:energy_acceptor` which acts internally like energy and item storage (for some reason). 

Try connect computer to any block described [here](https://docs.siredvin.site/UnlimitedPeripheralWorks/integrations/ae2/), for example, to any energy cell.
