### ISSUE TITLE
Item Count with "item_storage" type is reported as 1 when there's more

### ISSUE THREAD

**Issue by Infernalboy95000** [SirEdvin/UnlimitedPeripheralWorks#4]
Minecraft version: 1.19.2
Fabric api: 0.64.0
CC Restitched: 1.101.2
Peripheralium: 0.4.3
Peripheralworks: 0.2.1
Modern Industrialization: 1.3.2
Expanded Storage: 8.0.1
_Maybe missing some mod dependencies_

When using the command "peripheral.wrap("_side_").items()
with any storage on my mod list of type "item_storage", the "count" property is always reported as 1.

Here some screenShoots of my tests
Both the "Steel Barrel" and the "Expanded Storage Chest" are reported as "item_storage"

![report](https://user-images.githubusercontent.com/39791183/206907458-6a31e048-2193-47e5-bf4d-235acfc939a4.jpg)

_PD: I am not really sure if this is this mods fault, fabric storage api fault or both mods fault._

**Comment by SirEdvin** [comment]
Oh, that's seems huge .... I will try to solve this ...

**Comment by SirEdvin** [comment]
This fixed in 0.2.2 release
