### ISSUE TITLE
Fluid storage with multiple tanks causing fluid to not be consumed?

### ISSUE THREAD

**Issue by PalTheTaur** [SirEdvin/UnlimitedPeripheralWorks#41]
Not exactly sure if this is the exact issue, but when using the port of tinkers' construct [Hephaestus](https://modrinth.com/mod/hephaestus), attempting to transfer fluid out of the smeltery adds fluid to the transferred to tank, without taking fluid out of the smeltery, other mod's fluid transfer work, and tank to tank of tinkers' construct works with pushing fluids just fine. I don't really know any other fabric mods that support multiple tanks like tinkers' does, so its hard to test.

**Comment by SirEdvin** [comment]
So, I track down this issue to fabric code and it seems that Hephaestus implement logic for fabric incorrectly, because there is also [this](https://github.com/Alpha-s-Stuff/TinkersConstruct/issues/134) issue with same behavior but for different mods.

**Comment by SirEdvin** [comment]
btw, if you want, you can disable interaction with any Hephaestus blocks for UPW by adding `peripheralworks:ignore` tag to blocks that can expose fluid storage
