### ISSUE TITLE
CC:T 1.112.0 and Peripheralium Hub issues

### ISSUE THREAD

**Issue by superjaja05** [SirEdvin/UnlimitedPeripheralWorks#44]
Versions:
CC:T 1.112.0
UnlimitedPeripheralWorks 1.4.3
Forge 47.2.20
Minecraft 1.20.1

If you equip a modem (ender or regular) on a Pocket's Peripheralium Hub, the server crashes instantly
[crash-2024-08-06_04.40.28-server.txt](https://github.com/user-attachments/files/16504630/crash-2024-08-06_04.40.28-server.txt)

I did some testing, and rolling back to CC:T 1.111.0 fixes any crashing issue, so i suppose it's an issue with that CC:T update
The crash only happens on a pocket, on turtles the peripheralium hub works fine

And if the world has a pocket that already has a peripheralium hub + modem equipped, the server won't crash, but the pocket will never turn on

**Comment by SirEdvin** [comment]
Fixed in 1.4.4 release
