### ISSUE TITLE
AE2 API and peripheral integration

### ISSUE THREAD

**Issue by mblaze** [SirEdvin/UnlimitedPeripheralWorks#7]
I mainly use this integration to schedule some crafting depending on the number of resources available in my ME network. To do this well I need information about running crafting jobs. I find the current API to be either hard to use or lacking. I'd like you to consider three possible approaches to improving the current solution:
- improve and extend the current API
- design a new API learning from past mistakes of this and other mods that integrated CC with AE2
- implement the API defined in https://docs.intelligence-modding.de/1.19/peripherals/me_bridge/

IMO the third option has many advantages. It would allow users of that mod to easily transfer their programs, it is a more mature design and while the API is not perfect it has much more capabilities then the current one in the UPW.
Improving and extending the current API would be the most conservative option and would allow us to avoid breaking changes. This also means that we are stuck with the choices that were already made, whether they were good or not.
Designing a new API is hard but with some careful consideration it might give a better user experience.
Of course a hybrid approach is also possible.

Please consider the options and write back what do you think about it. I'll be glad to help with the implementation.

**Comment by SirEdvin** [comment]
tbh, I have no strict opinion about this, except reusing AdvancedPeripheral API, mostly because of exportItem/exportItemToPeripheral approach. 

However, idea to implement the rest of kit, especially item as a table seems like a nice idea. I have plans for expanding job managing logic in future releases in any case.

**Comment by SirEdvin** [comment]
So, new method `getActiveCraftings` will be introduced to close this gap. 
With this, I guess it should have at least feature-parity with AP API for now. If this is not true, please, reopen this issue.
