### ISSUE TITLE
AE2 fluid amount unit inconsistency

### ISSUE THREAD

**Issue by mblaze** [SirEdvin/UnlimitedPeripheralWorks#8]
The AE2 auto-crafting scheduling API for fluids deals with the fabric fluid units (81 000 per bucket) while the tanks API which is used to retrieve information about fluids stored in an ME network uses mB (1000 per bucket). IMO this makes it unnecessarily hard to use the API. I'd suggest that the auto-crafting scheduling API should be adjusted to use mB. If you agree I can contribute the fix.

**Comment by SirEdvin** [comment]
Yes, it definitely should.

**Comment by SirEdvin** [comment]
Okey, this fixed in 0.2.2 release
